name: diagnostic-demand
channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip

  # Data Handling
  - pandas
  - numpy
  - pyarrow
  - openpyxl
  - pyxlsb
  - tqdm
  - rich
  - requests
  - pyogrio

  # Geospatial Analysis
  - geopandas
  - shapely
  - pyproj
  - contextily
  - folium
  - geopy
  - rasterio
  - fiona
  - mapclassify
  - osmnx
  - r5py
  - libpysal
  - spint
  - spreg
  - esda
  - spaghetti

  # Visualisation
  - matplotlib
  - seaborn
  - plotly
  - colorcet
  - ipywidgets
  - jupyterlab
  - ipykernel
  - notebook

  # Machine Learning & Modelling
  - scikit-learn
  - xgboost
  - lightgbm
  - catboost
  - statsmodels
  - pmdarima
  - prophet
  - tensorflow
  - keras
  - networkx
  - pytorch::pytorch

  # Simulation / Optimisation
  - simpy
  - mesa
  - scipy
  - salib
  - joblib

  # Clustering & Dimensionality Reduction
  - umap-learn
  - hdbscan
  - yellowbrick
  - fastdtw

  # NLP & String Matching
  - nltk
  - spacy
  - rapidfuzz

  # Web App / Streamlit
  - streamlit
  - streamlit-folium
  - pydeck

  # Testing & Dev Utilities
  - pytest
  - pytest-cov
  - black
  - isort
  - ruff
  - mypy
  - pre-commit

  # Pip-only extras (validated)
  - pip:
      - torch-geometric
      - torch-scatter
      - torch-sparse
      - pymob
      - openrouteservice
      - streamlit-option-menu
      - jenkspy
      - kaleido
      - pyrosm
      - geoplot
      - momepy
      # segment-anything removed due to Python version conflict
